### ISSUE TITLE
Possible README.md typo

### ISSUE THREAD

**Issue by torchhound** [jpt4/prc#1]
"The directory theory is everything which does not execute (prose), **nn**practice everything that does (code). Meta-data and compliance documents (etc.) may not follow this schema."

I'm not sure whether this was a typo or simply something that is unclear in either case I felt I should bring it to your attention.

**Comment by torchhound** [comment]
"By "component-wise", reconfigurability is an atomic operation; a UC must be the least viable **semntic** element, such that if it were decomposed further it would not retain the complete set of properties guaranteed above."

semantic?

**Comment by torchhound** [comment]
"theory/{gelc-universality.txt, figures.pdf} are a note and associated diagrams describing the relation between RLEMs and GELCs in greater **(though yet terse)** detail, proving by construction the universality of RLEM-based Universal Cells."

I feel as though the grammar usage is a little odd here and could perhaps use some revision.

**Comment by jpt4** [comment]
_The frissonic feeling of the many-eyeballed stare of open source peer review._

Thank you for noticing these doc bugs. They are swatted in the latest commit.
